# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/wxfetcher.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc/wxfetcher.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13rpc/wxfetcher.proto\"&\n\x0f\x46\x65tchURLRequest\x12\x13\n\x0boriginalUrl\x18\x01 \x01(\t\"(\n\x10\x46\x65tchURLResponse\x12\x14\n\x0cshortenedKey\x18\x01 \x01(\t2>\n\tWxFetcher\x12\x31\n\x08\x46\x65tchURL\x12\x10.FetchURLRequest\x1a\x11.FetchURLResponse\"\x00\x62\x06proto3')
)




_FETCHURLREQUEST = _descriptor.Descriptor(
  name='FetchURLRequest',
  full_name='FetchURLRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='originalUrl', full_name='FetchURLRequest.originalUrl', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=61,
)


_FETCHURLRESPONSE = _descriptor.Descriptor(
  name='FetchURLResponse',
  full_name='FetchURLResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shortenedKey', full_name='FetchURLResponse.shortenedKey', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['FetchURLRequest'] = _FETCHURLREQUEST
DESCRIPTOR.message_types_by_name['FetchURLResponse'] = _FETCHURLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FetchURLRequest = _reflection.GeneratedProtocolMessageType('FetchURLRequest', (_message.Message,), dict(
  DESCRIPTOR = _FETCHURLREQUEST,
  __module__ = 'rpc.wxfetcher_pb2'
  # @@protoc_insertion_point(class_scope:FetchURLRequest)
  ))
_sym_db.RegisterMessage(FetchURLRequest)

FetchURLResponse = _reflection.GeneratedProtocolMessageType('FetchURLResponse', (_message.Message,), dict(
  DESCRIPTOR = _FETCHURLRESPONSE,
  __module__ = 'rpc.wxfetcher_pb2'
  # @@protoc_insertion_point(class_scope:FetchURLResponse)
  ))
_sym_db.RegisterMessage(FetchURLResponse)



_WXFETCHER = _descriptor.ServiceDescriptor(
  name='WxFetcher',
  full_name='WxFetcher',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=105,
  serialized_end=167,
  methods=[
  _descriptor.MethodDescriptor(
    name='FetchURL',
    full_name='WxFetcher.FetchURL',
    index=0,
    containing_service=None,
    input_type=_FETCHURLREQUEST,
    output_type=_FETCHURLRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WXFETCHER)

DESCRIPTOR.services_by_name['WxFetcher'] = _WXFETCHER

# @@protoc_insertion_point(module_scope)
