# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wxfetcher.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/wxfetcher.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('Z\005proto'),
  serialized_pb=_b('\n\x15proto/wxfetcher.proto\"\x1e\n\x0f\x46\x65tchURLRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\";\n\x10\x46\x65tchURLResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x04meta\x18\x02 \x01(\x0b\x32\x0c.ArticleMeta\"k\n\x0b\x41rticleMeta\x12\x0c\n\x04link\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\r\n\x05image\x18\x05 \x01(\t\x12\r\n\x05\x62rief\x18\x06 \x01(\t2>\n\tWxFetcher\x12\x31\n\x08\x46\x65tchURL\x12\x10.FetchURLRequest\x1a\x11.FetchURLResponse\"\x00\x42\x07Z\x05protob\x06proto3')
)




_FETCHURLREQUEST = _descriptor.Descriptor(
  name='FetchURLRequest',
  full_name='FetchURLRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='FetchURLRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=55,
)


_FETCHURLRESPONSE = _descriptor.Descriptor(
  name='FetchURLResponse',
  full_name='FetchURLResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='FetchURLResponse.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta', full_name='FetchURLResponse.meta', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=116,
)


_ARTICLEMETA = _descriptor.Descriptor(
  name='ArticleMeta',
  full_name='ArticleMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='link', full_name='ArticleMeta.link', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='ArticleMeta.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author', full_name='ArticleMeta.author', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ArticleMeta.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='ArticleMeta.image', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brief', full_name='ArticleMeta.brief', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=225,
)

_FETCHURLRESPONSE.fields_by_name['meta'].message_type = _ARTICLEMETA
DESCRIPTOR.message_types_by_name['FetchURLRequest'] = _FETCHURLREQUEST
DESCRIPTOR.message_types_by_name['FetchURLResponse'] = _FETCHURLRESPONSE
DESCRIPTOR.message_types_by_name['ArticleMeta'] = _ARTICLEMETA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FetchURLRequest = _reflection.GeneratedProtocolMessageType('FetchURLRequest', (_message.Message,), dict(
  DESCRIPTOR = _FETCHURLREQUEST,
  __module__ = 'proto.wxfetcher_pb2'
  # @@protoc_insertion_point(class_scope:FetchURLRequest)
  ))
_sym_db.RegisterMessage(FetchURLRequest)

FetchURLResponse = _reflection.GeneratedProtocolMessageType('FetchURLResponse', (_message.Message,), dict(
  DESCRIPTOR = _FETCHURLRESPONSE,
  __module__ = 'proto.wxfetcher_pb2'
  # @@protoc_insertion_point(class_scope:FetchURLResponse)
  ))
_sym_db.RegisterMessage(FetchURLResponse)

ArticleMeta = _reflection.GeneratedProtocolMessageType('ArticleMeta', (_message.Message,), dict(
  DESCRIPTOR = _ARTICLEMETA,
  __module__ = 'proto.wxfetcher_pb2'
  # @@protoc_insertion_point(class_scope:ArticleMeta)
  ))
_sym_db.RegisterMessage(ArticleMeta)


DESCRIPTOR._options = None

_WXFETCHER = _descriptor.ServiceDescriptor(
  name='WxFetcher',
  full_name='WxFetcher',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=227,
  serialized_end=289,
  methods=[
  _descriptor.MethodDescriptor(
    name='FetchURL',
    full_name='WxFetcher.FetchURL',
    index=0,
    containing_service=None,
    input_type=_FETCHURLREQUEST,
    output_type=_FETCHURLRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WXFETCHER)

DESCRIPTOR.services_by_name['WxFetcher'] = _WXFETCHER

# @@protoc_insertion_point(module_scope)
